### ISSUE TITLE
Python3 deletes config-file

### ISSUE THREAD

**Issue by umlaeute** [iem-projects/striem#27]
When running striem with `Python3` and doing a `File->Quit`, the config-file (as passed with `--config`) is emptied!

see also #26

**Comment by umlaeute** [comment]
here's a backtrace:

~~~sh
Traceback (most recent call last):
  File "/home/iem/schubert18/striem/striem/gui/striem.py", line 151, in exit
    self.streamer.teardown()
  File "/home/iem/schubert18/striem/striem/core/streamer.py", line 64, in teardown
    self.cfg.save()
  File "/home/iem/schubert18/striem/striem/core/configuration.py", line 127, in save
    self._cfg.write(configfile)
  File "/usr/lib/python3.5/configparser.py", line 916, in write
    self._sections[section].items(), d)
  File "/usr/lib/python3.5/configparser.py", line 920, in _write_section
    fp.write("[{}]\n".format(section_name))
TypeError: a bytes-like object is required, not 'str'
Terminated
~~~
